### ISSUE TITLE
Get watch sound alerts to play on windows machines

### ISSUE THREAD

**Issue by SEGEEK** [jamesshore/livestream#2]
Hi @jamesshore I did some research on the sound playing for windows I have something that works but the windows player limitation is that it only plays .wav files (it invokes powershell which is a standard component in windows machines now, playing mp3 would require downloading a binary for windows to execute or doing some magic with a headless electon app but that seems like overkill for the goal here).  According to what I have read online the 'afplay' command used on the mac will play '.wav' files but I was curious if you could confirm that for me.  I would like to make a PR where I convert the existing files to .wav format so the same files are used for both mac and windows, but wanted to check with you first before I did that.  An alternative I could do would be to just have a separate set of .wav files and in the watch script determine which files to play based on the event that happened and what system it is running on.

I don't mind doing either one just wanted to consult with you first so I don't take an approach you have issues with.  (BTW I am Pelyt on twitch).

**Comment by SEGEEK** [comment]
Created #3 to handle this.

**Comment by jamesshore** [comment]
Thanks, @SEGEEK, I'm looking at integrating your pull requests now.

**Comment by jamesshore** [comment]
This is done and will be uploaded before the next livestream. I've only checked it on MacOS, but I'm assuming @SEGEEK checked it on Windows.

**Comment by wolfgang-wdw** [comment]
Hi James, 
thanks for doing these videos, very helpful indeed!
Not sure if you are even looking for this kind of feedback, but just as an aside, I had an itch to reproduce the range/act/assert  behavior in _app.test.js uing sinon. Only setup and assertOutput need to be changed:

```
function setup(args) {
  const commandLine = sinon.stub(CommandLine.create());
  const app = App.create(commandLine);

  commandLine.args.returns(args);

  return { commandLine, app };
}

function assertOutput(commandLine, expectedOutput) {
  sinon.assert.calledWith(commandLine.writeOutput, expectedOutput);
}
```

I admit it still seems weird to have a "stub" be able to assert calls, which makes the td version a bit clearer.
